name = "yodel"
version = "1.0.1"

description = "A type-safe configuration loader for Gleam that handles JSON, YAML, and TOML with environment variable resolution."
licences = ["Apache-2.0"]
repository = { type = "github", user = "fluximus-prime", repo = "yodel" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
glaml = ">= 3.0.0 and < 4.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
simplifile = ">= 2.2.0 and < 3.0.0"
tom = ">= 0.3.0 and < 3.0.0"
gleam_regexp = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
startest = "== 0.6.0"
